# Name of our action
name: Storybook Release

# The event that will trigger the action
on:
  push:
    branches: [storybook]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

# What the action will do
jobs:
  # Build and deploy the Storybook
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    name: Build and Deploy Storybook
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.REPO_GIT_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: '/' # App source code path
          output_location: '/storybook-static' # Built app content directory - optional
